export enum MutationKey {
  SIGNIN = "signin",
  SIGNUP = "signup",
  LOGOUT = "logout",
  THIRD_PARTY_AUTH = "third-party-auth",
  UPLOAD_SONG_INFO = "upload-song-info",
  UPLOAD_SONG_FILE = "upload-song-file",
  UPLOAD_IMAGE_FILE = "upload-image-file",
  CREATE_NEW_SONG = "create-new-song",
  CREATE_USER_PLAYLIST = "create-user-playlist",
  UPDATE_PLAYLIST = "update-playlist",
  DELETE_PLAYLIST = "delete-playlist",
  REMOVE_PLAYLIST_FROM_PROFILE = "remove-playlist-from-profile",
  ADD_PLAYLIST_TO_PROFILE = "add-playlist-to-profile",
  CREATE_LABEL_OPTION = "create-label-option",
  REMOVE_LABEL_OPTION = "remove-label-option",
  CREATE_ALBUM_OPTION = "create-album-option",
  UPDATE_ALBUM_OPTION = "update-album-option",
  REMOVE_ALBUM_OPTION = "remove-album-option",
  DELETE_ALBUM_OPTION = "delete-album-option",
  UPDATE_USER = "update-user",
  DEREGISTER_USER = "deregister-user",
  RECORD_PLAYBACK_LOG = "record-playback-log",
  SEND_VERIFICATION_CODE = "send-verification-code",
  RESEND_VERIFICATION_CODE = "resend-verification-code",
  SEND_RESET_PASSWORD_EMAIL = "send-reset-password-email",
  VERIFY_VERIFICATION_CODE = "verify-verification-code",
  RESET_USER_PASSWORD = "reset-user-password",
  CHANGE_USER_PASSWORD = "change-user-password",
  UPDATE_USER_PREFERENCES = "update-user-preferences",
  SIGN_OUT_DEVICES = "sign-out-devices",
  SIGN_OUT_TARGET_DEVICE = "sign-out-target-device",
  TOUCH_SESSION_HEARTBEAT = "touch-session-heartbeat",
  RATE_SONG = "rate-song",
  DELETE_TARGET_SONG = "delete-target-song",
  ASSIGN_SONG_TO_PLAYLISTS = "assign-song-to-playlists",
  UPDATE_TARGET_SONG_INFO = "update-target-song-info",
  UPDATE_TARGET_MUSICIAN_INFO = "update-target-musician-info",
  FOLLOW_TARGET_MUSICIAN = "follow-target-musician",
  UNFOLLOW_TARGET_MUSICIAN = "unfollow-target-musician",
  CREATE_NOTIFICATION = "create-notification",
  MARK_NOTIFICATIONS_AS_VIEWED = "mark-notifications-as-viewed",
  MARK_NOTIFICATIONS_AS_READ = "mark-notifications-as-read",
  DELETE_TARGET_NOTIFICATION = "delete-target-notification",
}

export enum QueryKey {
  GET_AUTH_USER_INFO = "get-auth-user-info",
  GET_PROFILE_USER_INFO = "get-profile-user-info",
  GET_PROFILE_COLLECTION_INFO = "get-profile-collection-info",
  GET_USER_PREFERENCES = "get-user-preferences",
  GET_USER_SESSIONS = "get-user-sessions",

  VERIFY_RESET_PASSWORD_LINK = "verify-reset-password-link",

  GET_USER_PLAYLISTS = "get-user-playlists",
  GET_TARGET_PLAYLIST = "get-target-playlist",
  GET_PLAYLIST_PRIVACY_COUNTS = "get-playlist-privacy-counts",

  GET_ALL_SONGS = "get-all-songs",
  GET_USER_SONGS = "get-user-songs",
  GET_TARGET_SONG = "get-target-song",
  GET_QUERY_SONGS = "get-query-songs",
  GET_RECOMMENDED_SONGS = "get-recommended-songs",
  GET_USER_SONGS_STATS = "get-user-songs-stats",

  GET_USER_ALBUMS = "get-user-albums",
  GET_TARGET_ALBUM = "get-target-album",
  GET_RECOMMENDED_ALBUMS = "get-recommended-albums",

  GET_IP_GEOLOCATION = "get-ip-geolocation",
  GET_TARGET_MUSICIAN = "get-target-musician",
  GET_FOLLOWING_MUSICIANS = "get-following-musicians",
  GET_RECOMMENDED_MUSICIANS = "get-recommended-musicians",

  GET_USER_NOTIFICATIONS_BY_TYPE = "get-user-notifications-by-type",
  GET_USER_NOTIFICATION_TYPE_COUNTS = "get-user-notification-type-counts",
  GET_USER_UNVIEWED_NOTIFICATION_COUNT = "get-user-unviewed-notification-count",

  GET_USER_MONTHLY_STATS = "get-user-monthly-stats",
  GET_USER_SONG_RATING = "get-user-song-rating",

  GET_SEARCH_CONTENT_BY_TYPE = "get-search-content-by-type",

  GET_TARGET_LABEL = "get-target-label",
  GET_GENRE_LABELS = "get-genre-labels",
  GET_UPLOAD_SONG_LABELS = "get-upload-song-labels",
  GET_RECOMMENDED_LABELS = "get-recommended-labels",

  GET_POPULAR_MUSICIANS = "get-popular-musicians",
  GET_RECENTLY_PLAYED_SONGS = "get-recently-played-songs",
  GET_HOMEPAGE_RECOMMENDED_SONGS = "get-homepage-recommended-songs",
  GET_HOMEPAGE_RECOMMENDED_ALBUMS = "get-homepage-recommended-albums",
  GET_HOMEPAGE_RECOMMENDED_LABELS = "get-homepage-recommended-labels",
}
